version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular:
    build: ./frontend-angular
    ports:
      - "4200:4200"

  loopback:
    build: ./backend-loopback # specify the directory of the Dockerfile
    ports:
      - "3000:3000"
    links:
      - database
    #depends_on:
    #  - database

  database:
    image: mongo
    #volumes:
    #  - "/data/db:/data/db"
    ports:
      - "27017:27017"

  nginx: #name of the second service
    build: ./loadbalancer # specify the directory of the Dockerfile
    ports:
      - "80:8000" #specify ports forewarding
    links:
      - angular
      - loopback
