version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  #angular:
  #  build: ./frontend-angular
  #  ports:
  #    - "4200:4200"

  backend:
    build: ./backend # specify the directory of the Dockerfile
    ports:
      - "3000:3000"
    environment:
      - APP_NAME=pfeeder
      - JWT_SECRET=PUT_HERE_YOUR_JWT_SECRET
      - MONGO_HOST=database
      - MONGO_PASSWORD=pfeeder
      - MONGO_USERNAME=pfeeder_admin
      - REDIS_HOST=redis
      - MQTT_URI=mqtt://mosquitto
    links:
      - database
      - redis
      - mosquitto
    depends_on:
      - database
      - redis
      - mosquitto

  database:
    image: mongo
    #environment:
    #  - MONGO_INITDB_DATABASE=pfeeder
    #  - MONGO_NON_ROOT_USERNAME=pfeeder_admin
    #  - MONGO_NON_ROOT_PASSWORD=pfeeder
    #  - MONGO_INITDB_ROOT_USERNAME=pfeeder_admin
    #  - MONGO_INITDB_ROOT_PASSWORD=pfeeder
    volumes:
      - pfeeder-db:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis
    volumes:
      - redis-vol:/data
    ports:
      - "6379:6379"

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      #- ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    ports:
      - "1883:1883"

        #nginx: #name of the second service
        #  build: ./loadbalancer # specify the directory of the Dockerfile
        #  ports:
        #    - "80:8080" #specify ports forewarding
        #  links:
        #    - angular
        #    - loopback
volumes:
  pfeeder-db:
  redis-vol:
  mosquitto-data:
  mosquitto-log:

