openapi: '3.0.0'
info:
  version: 1.0.0
  title: Pfeeder
  description: A platform to automate the food feeding for your pets.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Pfeeder API Team
    email: nicolas.farabegoli@gmail.com
    url: http://pfeeder.nicolasfarabegoli.it
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://pfeeder.nicolasfarabegoli.it/v1

paths:
  $ref: "./paths/_index.yaml"

components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"


